name: Pytest Test Run with Allure Report

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from branch
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"

    - name: Upgrade & Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt

    - name: Playwright Install
      run: python -m playwright install --with-deps

    - name: Run Tests with Allure
      run: pytest -v --screenshot=on --browser=firefox --alluredir=allure-results

    - name: List Allure Results Directory
      run: ls -la allure-results

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
